### ISSUE TITLE
Publish official image to dockerhub

### ISSUE THREAD

**Issue by nicolai86** [influxdata/influxdb-docker#10]
would love to be able to just get this by using `docker run influxdata/influxdb`. 

Is there a reason for not making an official version available?

**Comment by jsternberg** [comment]
We are attempting to make this available on Docker Hub through adding it as an official image. See here for details: docker-library/official-images#1583.

**Comment by jsternberg** [comment]
The official image is published [here](https://hub.docker.com/_/influxdb/).
