### ISSUE TITLE
Not being able to pass arguments to influx 

### ISSUE THREAD

**Issue by dantespe** [influxdata/influxdb-docker#13]
There seems to be a bug in version 0.13 where I couldn't pass anything to influx for example:
$ influx -host hostname -database mydb  -username user -password abc

It keeps returning the error: "Failed to check token: invalid character 'M' looking for beginning of value.

When I try the same command on version 0.12 it works perfectly.

**Comment by jsternberg** [comment]
@dantespe that's because the server you are talking to is version 0.12. We changed the query endpoint to accept `POST` requests and switched the CLI to do that by default.

It's a bad error message.
